language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
  before_script:
     - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:28" --abi google_apis/armeabi-v7a
     - emulator -avd test -no-skin -no-audio -no-window &
     - android-wait-for-emulator
